### ISSUE TITLE
Question: how to add a plugin in the Coc Marketplace

### ISSUE THREAD

**Issue by antoinemadec** [fannheyward/coc-marketplace#115]
First, thanks for the great plugin!

I am the maintainer of [coc-fzf](https://github.com/antoinemadec/coc-fzf) and I was wondering:

1. if you were open to add this plugin in Coc Market place?
2. how to add a plugin in Coc Market place?

The goal here is to be able to do ```:CocInstall coc-fzf```.
See: https://github.com/antoinemadec/coc-fzf/issues/28

Thanks,
Antoine

**Comment by fannheyward** [comment]
1. `:CocInstall xxx` will install extension from npmjs.com, that means if you post your extension as a node package to npmjs, you can install it by `CocInstall`.
2. You can find all available coc extensions by https://www.npmjs.com/search?q=keywords:coc.nvim, if you put `coc.nvim` as package keywords. `coc-marketplace` just fetch this url and list extensions in coc-lists.
3. I don't think you can do `CocInstall coc-fzf`, because `coc-fzf` is not a node package. `CocInstall` just do npm/yarn install, ([code](https://github.com/neoclide/coc.nvim/blob/master/src/model/extension.ts#L126)) , the better way to install is using vim plugin manager, like `vim-plug`.
