### ISSUE TITLE
SSL version error

### ISSUE THREAD

**Issue by perfectspr** [fannheyward/coc-marketplace#31]
Got below error when using a proxy

>  2019-08-05T09:47:47.574 ERROR (pid:15235) [list-manager] - { Error: write EPROTO 4401731008:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:

coc-settings.json:
``` javascript
{
  "http.proxy": "proxyserver:8000",
  "http.proxyStrictSSL": false
}
```

**Comment by fannheyward** [comment]
The extension is using node's `http` module to make HTTP request, so the problem maybe caused by node.

According https://stackoverflow.com/questions/20841242/node-js-https-get-via-proxy-generates-ssl3-get-record-wrong-version-number-error , does your proxy server supports **HTTPS** proxy?  Or you can rm `http.proxyStrictSSL` from settings.
